Repository PI1-2024-1/PI1-KATIAU-docs, pull requests merged in 2024-05, with the labels that each got.

#1 Alteração da lista de intregrantes da equipe do projeto na aba inicial do pages.
  Eletronica/Esquemáticos/Segundo esquemático/Esquemático K.A.T.I.A.U.pdf
  Eletronica/Esquemáticos/Segundo esquemático/Segundo esquemático-backups/Segundo esquemático-2024-05-15_163509.zip
  Eletronica/Esquemáticos/Segundo esquemático/Segundo esquemático-backups/Segundo esquemático-2024-05-15_165153.zip
  Eletronica/Esquemáticos/Segundo esquemático/Segundo esquemático.kicad_sch
  Eletronica/Firmware/Robo_Seguidor_Linha/Robo_Seguidor_Linha.h
  Eletronica/Firmware/Robo_Seguidor_Linha/Robo_Seguidor_Linha.ino
  Eletronica/Firmware/Teste_ACS712/Teste_ACS712.ino
  Eletronica/Ponto de Controle 1/Diagramas/Diagrama Sistema de aquisição.png
  Eletronica/Ponto de Controle 1/Diagramas/Diagrama Sistema de movimento.png
  Eletronica/Ponto de Controle 1/Diagramas/Diagrama de Blocos.png
  Eletronica/Ponto de Controle 1/Diagramas/Diagrama sistema de comunicação.png
  Eletronica/Ponto de Controle 1/Diagramas/Diagrama sistema de medição.png
  Eletronica/README.md
  README.md
  docs/index.md
Labels: documentation, enhancement

#4 alterações no projeto conceitual
  docs/Documentacao/4_Conceitual.md
  docs/Documentacao/img/diagrama_classes.png
Labels: documentation

#5 Adição das atas de reunião de software dos dias 14.05 e 21.05
  docs/Atas/Reuniões Software/Reuniao_Software_2.md
  docs/Atas/Reuniões Software/Reuniao_Software_3.md
  docs/Documentacao/4_Conceitual.md
Labels: documentation

#3 Adição da ata da reunião 20.05
  docs/Atas/Gerais/Reuniao_Geral_2005.md
  docs/Atas/Gerais/Reuniao_Geral_3.md
  docs/Documentacao/6_Cronograma.md
  docs/index.md
Labels: documentation

#6 Adicionando arquitetura de software
  docs/Documentacao/4_Conceitual.md
  docs/Documentacao/img/diagrama_arquitetura.png
Labels: documentation, help wanted

#8 Ata da Reuniao_Geral_5
  docs/Atas/Gerais/Reuniao_Geral_5
Labels: documentation

#9 Correção Cronograma
  docs/Documentacao/6_Cronograma.md
Labels: documentation

#7 Commit para ajustes visuais verificados após ultimo PR.
  docs/Atas/Reuniões Software/Reuniao_Software_3.md
  docs/Documentacao/2_Tap.md
  docs/Documentacao/6_Cronograma.md
Labels: documentation, enhancement

#11 Update README.md
  README.md
Labels: documentation, enhancement

#13 Correção do quadro da equipe e separação em áreas
  README.md
  docs/index.md
Labels: bug, documentation

#14 Analise energetica
  docs/Documentacao/4_Conceitual.md
  docs/javascripts/mathjax.js
  mkdocs.yml
Labels: documentation, enhancement
